from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any


STATUS_MARKER = "CHRONICLE_STATUS"
STATUS_CANONICAL_NOTE = "> Chronicle generated view below is the canonical live status signal."


def projection_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _replace_marked_block(text: str, marker: str, block: str) -> str:
    begin = f"<!-- BEGIN GENERATED:{marker} -->"
    end = f"<!-- END GENERATED:{marker} -->"
    replacement = f"{begin}\n{block.rstrip()}\n{end}"

    if begin in text and end in text:
        start = text.index(begin)
        finish = text.index(end) + len(end)
        return text[:start].rstrip() + "\n\n" + replacement + "\n"

    base = text.rstrip()
    if base:
        base += "\n\n"
    return base + replacement + "\n"


def _normalize_status_preamble(text: str) -> str:
    lines = text.splitlines()
    if not lines:
        return text

    begin_marker = f"<!-- BEGIN GENERATED:{STATUS_MARKER} -->"
    marker_index = next((index for index, line in enumerate(lines) if line == begin_marker), len(lines))

    for index, line in enumerate(lines[:marker_index]):
        if line.startswith("> Last updated:"):
            lines[index] = line.replace("> Last updated:", "> Human summary last reviewed:", 1)
            break

    note_present = any(line == STATUS_CANONICAL_NOTE for line in lines[:marker_index])
    if not note_present:
        insert_at = 0
        if lines[0].startswith("#"):
            insert_at = 1
            while insert_at < marker_index and lines[insert_at].startswith(">"):
                insert_at += 1
            while insert_at < marker_index and lines[insert_at] == "":
                insert_at += 1
        lines[insert_at:insert_at] = [STATUS_CANONICAL_NOTE, ""]

    return "\n".join(lines).rstrip() + "\n"


def _pipeline_value(counts: dict[str, Any], *keys: str) -> int:
    for key in keys:
        value = counts.get(key)
        if isinstance(value, int):
            return value
    return 0


def render_job_search_status(snapshot: dict[str, Any], recent_events: list[dict[str, Any]]) -> str:
    openclaw = snapshot.get("openclaw", {})
    digest = snapshot.get("digest", {})
    counts = openclaw.get("pipeline_counts") or {}
    top_leads = openclaw.get("top_leads") or []
    found_count = _pipeline_value(counts, "found", "new") or int(openclaw.get("lead_count") or 0)

    lines = [
        "# Job Search Status",
        f"> Generated by Chronicle at {projection_timestamp()}",
        f"> Source snapshot: {snapshot.get('id')} ({snapshot.get('captured_at_local')})",
        "",
        "## Metrics",
        f"- Jobs found today: {openclaw.get('jobs_found_today', 'unknown')}",
        f"- Applications sent today: {openclaw.get('applications_sent_today', 'unknown')}",
        f"- GPT calls today: {openclaw.get('gpt_calls_today', 'unknown')}",
        f"- Leads tracked: {openclaw.get('lead_count', 'unknown')}",
        "",
        "## Pipeline",
        f"- Found: {found_count}",
        f"- Shortlisted: {_pipeline_value(counts, 'shortlisted', 'ready')}",
        f"- CL written: {_pipeline_value(counts, 'cl_written', 'cl', 'cover_letter')}",
        f"- Applied: {_pipeline_value(counts, 'applied')}",
        f"- Responded: {_pipeline_value(counts, 'responded', 'response')}",
        f"- Interviews: {_pipeline_value(counts, 'interview', 'interviews')}",
        "",
        "## System Health",
        f"- Scout: {openclaw.get('last_scout') or 'unknown'}",
        f"- Nightly: {openclaw.get('last_nightly') or 'unknown'}",
        f"- Backup: {openclaw.get('last_backup') or 'unknown'}",
        f"- GPT limit warning: {openclaw.get('gpt_limit_warning') or 'none'}",
        "",
        "## Top Leads",
        "| Company | Role | Status |",
        "|---------|------|--------|",
    ]

    if top_leads:
        for lead in top_leads[:5]:
            company = (lead.get("company") or "Unknown").replace("|", "/")
            role = (lead.get("role") or lead.get("title") or "Unknown role").replace("|", "/")
            status = (lead.get("status") or "unknown").replace("|", "/")
            lines.append(f"| {company} | {role} | {status} |")
    else:
        lines.append("| No leads captured | - | - |")

    lines.extend(
        [
            "",
            "## Recent Chronicle Events",
        ]
    )
    if recent_events:
        for entry in recent_events[:6]:
            lines.append(
                f"- {entry.get('recorded_at')} | {entry.get('category') or 'note'} | "
                f"{entry.get('project') or 'n/a'} | {entry.get('text')}"
            )
    else:
        lines.append("- No Chronicle events for job search yet.")

    lines.extend(
        [
            "",
            "## World Context",
        ]
    )
    headlines = digest.get("world_headlines") or []
    if headlines:
        for headline in headlines[:4]:
            lines.append(f"- {headline}")
    else:
        lines.append("- No digest headlines captured in the latest snapshot.")

    return "\n".join(lines).strip() + "\n"


def render_status_generated_block(
    snapshot: dict[str, Any],
    db_summary: dict[str, Any],
    recent_events: list[dict[str, Any]],
) -> str:
    portfolio = snapshot.get("portfolio_assets", {})
    openclaw = snapshot.get("openclaw", {})
    digest = snapshot.get("digest", {})

    lines = [
        "## Chronicle Generated View",
        f"> Generated: {projection_timestamp()}",
        f"> Source snapshot: {snapshot.get('id')} ({snapshot.get('captured_at_local')})",
        "",
        "### Chronicle Health",
        f"- Events: {db_summary.get('events', 0)}",
        f"- Snapshots: {db_summary.get('snapshots', 0)}",
        f"- Artifacts: {db_summary.get('artifacts', 0)}",
        f"- Artifact links: {db_summary.get('artifact_links', 0)}",
        f"- Relations: {db_summary.get('relations', 0)}",
        f"- Projection runs: {db_summary.get('projection_runs', 0)}",
        "",
        "### Live Runtime Summary",
        f"- Portfolio missing asset slots: {portfolio.get('missing_assets_total', 'unknown')}",
        f"- Portfolio OG images needed: {portfolio.get('og_images_needed', 'unknown')}",
        f"- OpenClaw jobs found today: {openclaw.get('jobs_found_today', 'unknown')}",
        f"- OpenClaw applications sent today: {openclaw.get('applications_sent_today', 'unknown')}",
        f"- OpenClaw GPT calls today: {openclaw.get('gpt_calls_today', 'unknown')}",
        f"- Digest status: {json.dumps(digest.get('status', {}), ensure_ascii=False)}",
        "",
        "### Recent Durable Events",
    ]

    if recent_events:
        for entry in recent_events[:8]:
            lines.append(
                f"- {entry.get('recorded_at')} | {entry.get('category') or 'note'} | "
                f"{entry.get('project') or 'n/a'} | {entry.get('text')}"
            )
    else:
        lines.append("- No Chronicle events captured yet.")

    lines.extend(
        [
            "",
            "### Evidence Paths",
            f"- OpenClaw state: {openclaw.get('state_path')}",
            f"- OpenClaw brief: {openclaw.get('brief_path')}",
            f"- Digest status: {digest.get('status_path')}",
            f"- Digest synthesis: {digest.get('synthesis_path')}",
            f"- Portfolio manifest: {portfolio.get('path')}",
        ]
    )
    return "\n".join(lines).strip()


def update_status_file(path: Path, block: str) -> str:
    current = path.read_text(encoding="utf-8")
    normalized = _normalize_status_preamble(current)
    updated = _replace_marked_block(normalized, STATUS_MARKER, block)
    path.write_text(updated, encoding="utf-8")
    return updated
